/*
- Emenda que, em modo de revisão, adiciona alguns dispositivos e modifica outros.
- As intervenções são feitas em dispositivos de norma alterada.
- Possui a inclusão de omissis.
*/
export const EMENDA_009 = {
  dataUltimaModificacao: '2023-08-08T23:08:02.002Z',
  aplicacao: '',
  versaoAplicacao: '',
  modoEdicao: 'emenda',
  metadados: {},
  proposicao: {
    urn: 'urn:lex:br:federal:medida.provisoria:2023-04-30;1171',
    sigla: 'MPV',
    numero: '1171',
    ano: '2023',
    ementa:
      'Dispõe sobre a tributação da renda auferida por pessoas físicas residentes no País em aplicações financeiras, entidades controladas e trusts no exterior, altera os valores da tabela mensal do Imposto sobre a Renda da Pessoa Física de que trata o art. 1º da Lei nº 11.482, de 31 de maio de 2007 , e altera os valores de dedução previstos no art. 4º da Lei nº 9.250, de 26 de dezembro de 1995 .',
    identificacaoTexto: 'Texto da MPV',
  },
  epigrafe: {
    texto: 'EMENDA Nº         - CMMPV 1171/2023',
    complemento: '(à MPV 1171/2023)',
  },
  componentes: [
    {
      urn: 'urn:lex:br:federal:medida.provisoria:2023-04-30;1171',
      articulado: true,
      dispositivos: {
        dispositivosSuprimidos: [],
        dispositivosModificados: [
          {
            tipo: 'Paragrafo',
            id: 'art14_cpt_alt1_art4_par1',
            rotulo: '§ 1º',
            texto:
              'A dedução permitida teste pelo inciso V do caput aplica-se exclusivamente à base de cálculo relativa aos seguintes rendimentos, assegurada, nos demais casos, a dedução dos valores pagos a esse título, por ocasião da apuração da base de cálculo do imposto devido no ano-calendário, conforme disposto na alínea “e” do inciso II do caput do art. 8º:',
            urnNormaAlterada: 'urn:lex:br:federal:lei:1995-12-26;9250',
          },
          {
            tipo: 'Paragrafo',
            id: 'art14_cpt_alt1_art4_par2',
            rotulo: '§ 2º',
            texto: '',
            urnNormaAlterada: 'urn:lex:br:federal:lei:1995-12-26;9250',
          },
        ],
        dispositivosAdicionados: [
          {
            tipo: 'Paragrafo',
            id: 'art13_cpt_alt1_art1u_par1u',
            rotulo: '§ 1º',
            texto: 'Novo parágrafo.',
            idIrmaoAnterior: 'art13_cpt_alt1_art1_omi1',
            urnNormaAlterada: 'urn:lex:br:federal:lei:2007-05-31;11482',
          },
          {
            tipo: 'Omissis',
            id: 'art13_cpt_alt1_art1u_omi2',
            fechaAspas: true,
            notaAlteracao: 'NR',
            idIrmaoAnterior: 'art13_cpt_alt1_art1u_par1u',
            urnNormaAlterada: 'urn:lex:br:federal:lei:2007-05-31;11482',
            existeNaNormaAlterada: true,
          },
          {
            tipo: 'Paragrafo',
            id: 'art14_cpt_alt1_art4_par1-1',
            rotulo: '§ 1º-A.',
            texto: 'Outro novo parágrafo.',
            idIrmaoAnterior: 'art14_cpt_alt1_art4_par1',
            urnNormaAlterada: 'urn:lex:br:federal:lei:1995-12-26;9250',
            existeNaNormaAlterada: true,
          },
          {
            tipo: 'Paragrafo',
            id: 'art14_cpt_alt1_art4_par1-2',
            rotulo: '§ 1º-B.',
            texto: 'Mais um parágrafo.',
            idIrmaoAnterior: 'art14_cpt_alt1_art4_par1-1',
            urnNormaAlterada: 'urn:lex:br:federal:lei:1995-12-26;9250',
          },
          {
            tipo: 'Paragrafo',
            id: 'art14_cpt_alt1_art4_par3',
            rotulo: '§ 3º',
            texto: 'E mais um parágrafo.',
            fechaAspas: true,
            notaAlteracao: 'NR',
            idIrmaoAnterior: 'art14_cpt_alt1_art4_par2',
            urnNormaAlterada: 'urn:lex:br:federal:lei:1995-12-26;9250',
          },
        ],
      },
    },
  ],
  comandoEmenda: {
    cabecalhoComum: 'Dê-se nova redação  à  Medida Provisória nos termos dos itens 1 e 2 a seguir.',
    comandos: [
      {
        cabecalho: 'Acrescente-se § 1º ao art. 1º da Lei nº 11.482, de 31 de maio de 2007, na forma proposta pelo art. 13 da Medida Provisória, nos termos a seguir:',
        citacao:
          '<p class="artigo">“<Rotulo>Art. 1º</Rotulo> <Omissis/></p><p class="omissis"><Omissis/></p><p classe="paragrafo"><Rotulo>§ 1º</Rotulo> Novo parágrafo.</p><p classe="omissis"> <Omissis/>” (NR)</p>',
        rotulo: 'Item 1 –',
      },
      {
        cabecalho:
          'Dê-se nova redação aos §§ 1º, 1º-A e 2º do art. 4º; e acrescentem-se §§ 1º-B e 3º ao art. 4º, todos da Lei nº 9.250, de 26 de dezembro de 1995, na forma proposta pelo art. 14 da Medida Provisória, nos termos a seguir:',
        citacao:
          '<p class="artigo">“<Rotulo>Art. 4º</Rotulo> <Omissis/></p><p class="omissis"><Omissis/></p><p classe="paragrafo"><Rotulo>§ 1º</Rotulo> A dedução permitida teste pelo inciso V do caput aplica-se exclusivamente à base de cálculo relativa aos seguintes rendimentos, assegurada, nos demais casos, a dedução dos valores pagos a esse título, por ocasião da apuração da base de cálculo do imposto devido no ano-calendário, conforme disposto na alínea “e do inciso II do caput do art. 8º:</p><p class="omissis"><Omissis/></p><p classe="paragrafo"><Rotulo>§ 1º-A.</Rotulo> Outro novo parágrafo.</p><p classe="paragrafo"><Rotulo>§ 1º-B.</Rotulo> Mais um parágrafo.</p><p classe="paragrafo"><Rotulo>§ 2º</Rotulo> </p><p classe="paragrafo"><Rotulo>§ 3º</Rotulo> E mais um parágrafo” (NR)</p>',
        rotulo: 'Item 2 –',
      },
    ],
  },
  justificativa: '',
  local: 'Sala da comissão',
  data: '2023-08-08',
  autoria: {
    tipo: 'Parlamentar',
    imprimirPartidoUF: true,
    quantidadeAssinaturasAdicionaisSenadores: 0,
    quantidadeAssinaturasAdicionaisDeputados: 0,
    parlamentares: [],
  },
  opcoesImpressao: {
    imprimirBrasao: true,
    textoCabecalho: '',
    reduzirEspacoEntreLinhas: false,
    tamanhoFonte: 14,
  },
  revisoes: [
    {
      type: 'RevisaoElemento',
      id: '6b48a089-1acf-487e-9a7f-8db4ebe4cdf8',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 19:58:53',
      descricao: 'Dispositivo adicionado',
      actionType: 'ADICIONAR_ELEMENTO',
      stateType: 'ElementoIncluido',
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 158,
        uuid2: '4ae9eecf-9404-49aa-a889-5e88ed9738d9',
        lexmlId: 'art13_cpt_alt1_art1u_par1u',
        conteudo: {
          texto: 'Novo parágrafo.',
        },
        descricaoSituacao: 'Dispositivo Adicionado',
        existeNaNormaAlterada: false,
        nivel: 2,
        numero: '1',
        rotulo: '§ 1º',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 133,
            uuid2: 'f2369a70-0707-41df-b2ed-a1999fa3603f',
            lexmlId: 'art13_cpt_alt1_art1',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 130,
            uuid2Alteracao: '7f1eaf5a-e764-4857-b46f-1869a3259a35',
          },
          posicao: 5,
          numero: '1',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
        elementoAnteriorNaSequenciaDeLeitura: {
          tipo: 'Omissis',
          uuid: 138,
          uuid2: 'bb0a4a70-b18e-4225-a4d0-9e63a08b0b93',
          lexmlId: 'art13_cpt_alt1_art1_omi1',
          conteudo: {
            texto:
              '.................................................................................................................................................................................................................................................................................',
          },
          descricaoSituacao: 'Dispositivo Original',
        },
      },
    },
    {
      type: 'RevisaoElemento',
      id: '317c44f9-7887-48b1-adeb-7c1d352bc738',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:00:06',
      descricao: 'Dispositivo adicionado',
      actionType: 'TRANSFORMAR_TIPO_ELEMENTO',
      stateType: 'ElementoIncluido',
      elementoAposRevisao: {
        tipo: 'Omissis',
        uuid: 160,
        uuid2: 'be84736f-63d3-481a-82f2-60be44d776e2',
        lexmlId: 'art13_cpt_alt1_art1u_omi2',
        conteudo: {
          texto:
            '.................................................................................................................................................................................................................................................................................',
        },
        descricaoSituacao: 'Dispositivo Adicionado',
        existeNaNormaAlterada: true,
        nivel: 2,
        rotulo: '',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 133,
            uuid2: 'f2369a70-0707-41df-b2ed-a1999fa3603f',
            lexmlId: 'art13_cpt_alt1_art1',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 130,
            uuid2Alteracao: '7f1eaf5a-e764-4857-b46f-1869a3259a35',
          },
          posicao: 6,
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: true,
        notaAlteracao: 'NR',
        dispositivoAlteracao: true,
        tipoOmissis: 'paragrafo',
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'a',
        elementoAnteriorNaSequenciaDeLeitura: {
          tipo: 'Paragrafo',
          uuid: 158,
          uuid2: '4ae9eecf-9404-49aa-a889-5e88ed9738d9',
          lexmlId: 'art13_cpt_alt1_art1u_par1u',
          conteudo: {
            texto: 'Novo parágrafo.',
          },
          descricaoSituacao: 'Dispositivo Adicionado',
          existeNaNormaAlterada: false,
        },
      },
    },
    {
      type: 'RevisaoElemento',
      id: '1fa4dbe8-aa08-4670-8cb9-960d1c88f742',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:00:52',
      descricao: 'Texto do dispositivo foi alterado',
      actionType: 'ATUALIZAR_TEXTO_ELEMENTO',
      stateType: 'ElementoModificado',
      elementoAntesRevisao: {
        tipo: 'Paragrafo',
        uuid: 145,
        uuid2: '256cbbf0-8949-41ba-a1a0-dc4653253fb2',
        lexmlId: 'art14_cpt_alt1_art4_par1',
        conteudo: {
          texto:
            'A dedução permitida pelo inciso V do caput aplica-se exclusivamente à base de cálculo relativa aos seguintes rendimentos, assegurada, nos demais casos, a dedução dos valores pagos a esse título, por ocasião da apuração da base de cálculo do imposto devido no ano-calendário, conforme disposto na alínea “e” do inciso II do caput do art. 8º:',
        },
        descricaoSituacao: 'Dispositivo Original',
        nivel: 2,
        numero: '1',
        rotulo: '§ 1º',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 1,
          numero: '1',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
      },
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 145,
        uuid2: '256cbbf0-8949-41ba-a1a0-dc4653253fb2',
        lexmlId: 'art14_cpt_alt1_art4_par1',
        conteudo: {
          texto:
            'A dedução permitida teste pelo inciso V do caput aplica-se exclusivamente à base de cálculo relativa aos seguintes rendimentos, assegurada, nos demais casos, a dedução dos valores pagos a esse título, por ocasião da apuração da base de cálculo do imposto devido no ano-calendário, conforme disposto na alínea “e” do inciso II do caput do art. 8º:',
        },
        descricaoSituacao: 'Dispositivo Modificado',
        nivel: 2,
        numero: '1',
        rotulo: '§ 1º',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 1,
          numero: '1',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
      },
    },
    {
      type: 'RevisaoElemento',
      id: 'dec88226-51a2-47b0-9581-af981ed3ce0a',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:05:11',
      descricao: 'Dispositivo adicionado',
      actionType: 'ADICIONAR_ELEMENTO',
      stateType: 'ElementoIncluido',
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 161,
        uuid2: 'd9616726-6268-45a1-b6f4-dca5bff75936',
        lexmlId: 'art14_cpt_alt1_art4_par1-1',
        conteudo: {
          texto: 'Outro novo parágrafo.',
        },
        descricaoSituacao: 'Dispositivo Adicionado',
        existeNaNormaAlterada: true,
        nivel: 2,
        numero: '1-1',
        rotulo: '§ 1º-A.',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 2,
          numero: '1-1',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
        elementoAnteriorNaSequenciaDeLeitura: {
          tipo: 'Inciso',
          uuid: 147,
          uuid2: '17da383a-fb6c-4c72-83ed-72b04cafb19f',
          lexmlId: 'art14_cpt_alt1_art4_par1_inc2',
          conteudo: {
            texto: 'proventos de aposentados e pensionistas, quando a fonte pagadora for responsável pelo desconto e pelo respectivo pagamento das contribuições previdenciárias.',
          },
          descricaoSituacao: 'Dispositivo Original',
        },
      },
    },
    {
      type: 'RevisaoElemento',
      id: '6a2f84ac-c5dd-4998-a4f7-4a95af9c82a0',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:05:34',
      descricao: 'Dispositivo adicionado',
      actionType: 'ADICIONAR_ELEMENTO',
      stateType: 'ElementoIncluido',
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 162,
        uuid2: '8dc78652-d2c2-4642-8a7a-21c59e91f55e',
        lexmlId: 'art14_cpt_alt1_art4_par1-2',
        conteudo: {
          texto: 'Mais um parágrafo.',
        },
        descricaoSituacao: 'Dispositivo Adicionado',
        existeNaNormaAlterada: false,
        nivel: 2,
        numero: '1-2',
        rotulo: '§ 1º-B.',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 3,
          numero: '1-2',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
        elementoAnteriorNaSequenciaDeLeitura: {
          tipo: 'Paragrafo',
          uuid: 161,
          uuid2: 'd9616726-6268-45a1-b6f4-dca5bff75936',
          lexmlId: 'art14_cpt_alt1_art4_par1-1',
          conteudo: {
            texto: 'Outro novo parágrafo.',
          },
          descricaoSituacao: 'Dispositivo Adicionado',
          existeNaNormaAlterada: true,
        },
      },
    },
    {
      type: 'RevisaoElemento',
      id: '47f50d9b-7e98-4c66-9ea8-270a99528c4e',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:06:38',
      descricao: 'Dispositivo adicionado',
      actionType: 'ADICIONAR_ELEMENTO',
      stateType: 'ElementoIncluido',
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 163,
        uuid2: 'b282816f-941e-4e9c-b9bf-5cd098dfcb47',
        lexmlId: 'art14_cpt_alt1_art4_par3',
        conteudo: {
          texto: 'E mais um parágrafo',
        },
        descricaoSituacao: 'Dispositivo Adicionado',
        existeNaNormaAlterada: false,
        nivel: 2,
        numero: '3',
        rotulo: '§ 3º',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 5,
          numero: '3',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: true,
        notaAlteracao: 'NR',
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
      },
    },
    {
      type: 'RevisaoElemento',
      id: 'c5900b09-de32-491e-a635-71ad098cb24d',
      usuario: {
        nome: 'Anônimo',
      },
      dataHora: '2023-08-08 20:07:29',
      descricao: 'Texto do dispositivo foi alterado',
      actionType: 'ATUALIZAR_TEXTO_ELEMENTO',
      stateType: 'ElementoModificado',
      elementoAntesRevisao: {
        tipo: 'Paragrafo',
        uuid: 148,
        uuid2: 'ff7bf824-f144-4ade-ba11-93610ffdf5c8',
        lexmlId: 'art14_cpt_alt1_art4_par2',
        conteudo: {
          texto:
            'Alternativamente às deduções de que trata o caput, poderá ser utilizado desconto simplificado mensal, correspondente a 25% (vinte e cinco por cento) do valor máximo da faixa com alíquota zero da tabela progressiva mensal, caso seja mais benéfico ao contribuinte, dispensadas a comprovação da despesa e a indicação de sua espécie.',
        },
        descricaoSituacao: 'Dispositivo Original',
        nivel: 2,
        numero: '2',
        rotulo: '§ 2º',
        agrupador: false,
        editavel: true,
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 4,
          numero: '2',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
      },
      elementoAposRevisao: {
        tipo: 'Paragrafo',
        uuid: 148,
        uuid2: 'ff7bf824-f144-4ade-ba11-93610ffdf5c8',
        lexmlId: 'art14_cpt_alt1_art4_par2',
        conteudo: {
          texto: '',
        },
        descricaoSituacao: 'Dispositivo Modificado',
        nivel: 2,
        numero: '2',
        rotulo: '§ 2º',
        agrupador: false,
        editavel: true,
        mensagens: [
          {
            tipo: 'ERROR',
            descricao: 'Não foi informado um texto para o parágrafo.',
          },
        ],
        hierarquia: {
          pai: {
            tipo: 'Artigo',
            uuid: 143,
            uuid2: '8dba89f6-fba9-4938-b398-bffe1caa8f0a',
            lexmlId: 'art14_cpt_alt1_art4',
            descricaoSituacao: 'Dispositivo Original',
            uuidAlteracao: 140,
            uuid2Alteracao: 'eb85d46b-5f13-4436-86f1-b76e5262ae1f',
          },
          posicao: 4,
          numero: '2',
        },
        sendoEditado: false,
        index: 0,
        abreAspas: false,
        fechaAspas: false,
        dispositivoAlteracao: true,
        podeEditarNotaAlteracao: false,
        manterNoMesmoGrupoDeAspas: false,
        artigoDefinido: 'o',
      },
    },
  ],
  colegiadoApreciador: {
    siglaCasaLegislativa: 'CN',
    tipoColegiado: 'Comissão',
    siglaComissao: 'CMMPV 1171/2023',
  },
};
