/* eslint-disable prettier/prettier */
export const mps2020 = [
  {
    idIdentificacao: 7859499,
    descricaoIdentificacao: 'MPV 918/2020',
    descricaoIdentificacaoExtensa: 'Medida Provisória n° 918, de 2020',
    sigla: 'MPV',
    numero: '00918',
    ano: 2020,
    idProcesso: 7859496,
    idDocumentoManifestacao: 8060641,
    codMateriaMigradaMATE: 140394,
    emElaboracao: false,
    estadoProposicao: 'Encerrado',
    ementa: 'Cria funções de confiança destinadas à Polícia Federal e extingue cargos em comissão.',
    dataLeitura: null,
    idDocumentoItemDigital: null,
    idSdlegDocumentoItemDigital: null,
    urlDownloadItemDigitalZip: null,
    dataPublicacao: null,
    dataLimiteRecebimentoEmendas: null,
    labelPrazoRecebimentoEmendas: 'encerrado',
    labelTramitacao: '',
  },
  {
    idIdentificacao: 7859935,
    descricaoIdentificacao: 'MPV 919/2020',
    descricaoIdentificacaoExtensa: 'Medida Provisória n° 919, de 2020',
    sigla: 'MPV',
    numero: '00919',
    ano: 2020,
    idProcesso: 7859932,
    idDocumentoManifestacao: 8061003,
    codMateriaMigradaMATE: 140423,
    emElaboracao: false,
    estadoProposicao: 'Encerrado',
    ementa: 'Dispõe sobre o valor do salário mínimo a vigorar a partir de 1º de fevereiro de 2020.',
    dataLeitura: null,
    idDocumentoItemDigital: 1242832790419,
    idSdlegDocumentoItemDigital: '402775cf-10dc-4245-a32a-a473724b7f9a',
    urlDownloadItemDigitalZip: 'https://legis.senado.gov.br/sdleg-getter/documento/download/402775cf-10dc-4245-a32a-a473724b7f9a',
    dataPublicacao: null,
    dataLimiteRecebimentoEmendas: null,
    labelPrazoRecebimentoEmendas: 'encerrado',
    labelTramitacao: '',
  },
  {
    idIdentificacao: 7859942,
    descricaoIdentificacao: 'MPV 920/2020',
    descricaoIdentificacaoExtensa: 'Medida Provisória n° 920, de 2020',
    sigla: 'MPV',
    numero: '00920',
    ano: 2020,
    idProcesso: 7859939,
    idDocumentoManifestacao: 8061005,
    codMateriaMigradaMATE: 140424,
    emElaboracao: false,
    estadoProposicao: 'Encerrado',
    ementa: 'Abre crédito extraordinário, em favor do Ministério do Desenvolvimento Regional, no valor de R$892.000.000,00, para os fins que especifica.',
    dataLeitura: null,
    idDocumentoItemDigital: null,
    idSdlegDocumentoItemDigital: null,
    urlDownloadItemDigitalZip: null,
    dataPublicacao: null,
    dataLimiteRecebimentoEmendas: null,
    labelPrazoRecebimentoEmendas: 'encerrado',
    labelTramitacao: '',
  },
  {
    idIdentificacao: 7863256,
    descricaoIdentificacao: 'MPV 921/2020',
    descricaoIdentificacaoExtensa: 'Medida Provisória n° 921, de 2020',
    sigla: 'MPV',
    numero: '00921',
    ano: 2020,
    idProcesso: 7863253,
    idDocumentoManifestacao: 8063840,
    codMateriaMigradaMATE: 140592,
    emElaboracao: false,
    estadoProposicao: 'Encerrado',
    ementa: 'Abre crédito extraordinário, em favor do Ministério da Defesa, no valor de R$ 11.287.803,00, para os fins que especifica.',
    dataLeitura: null,
    idDocumentoItemDigital: null,
    idSdlegDocumentoItemDigital: null,
    urlDownloadItemDigitalZip: null,
    dataPublicacao: null,
    dataLimiteRecebimentoEmendas: null,
    labelPrazoRecebimentoEmendas: 'encerrado',
    labelTramitacao: '',
  },
];
